### ISSUE TITLE
Suggestion: add method name to table

### ISSUE THREAD

**Issue by mengxiao** [vanallenlab/firecloud-helper#7]

**Comment by brendanreardon** [comment]
Can you expand upon this, @mengxiao?

**Comment by brendanreardon** [comment]
One thought is perhaps you mean to change the index file to list two columns instead of just one, with the new column displaying the method name. This may not be too difficult. I think that it would just be hitting the submissions endpoint and then do string matching. 

Alternatively I am wondering if you mean for the search results on the compute website. I have an issue open for that [here](https://github.com/vanallenlab/nsght-web/issues/5). One problem though is that terra will append an underscore followed by a random string of 11 characters to method names, which makes searching by methods difficult.

**Comment by mengxiao** [comment]
I just want to see it in the table output in the UI. I don't need to be able to search, and I'm ok with the Terra random suffix added to old versions of methods.

**Comment by brendanreardon** [comment]
Oh okay, so did you mean to post this Issue in the other repo then? This is under the storage cleaner's repo.

**Comment by brendanreardon** [comment]
None the less, happy to make that change :)

**Comment by brendanreardon** [comment]
Done https://github.com/vanallenlab/nsght-web/commit/1090386ed18c7f0e4daf2597ef9ccace12c20757
